name: PullRequest
on: [ pull_request ]
jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_next_version.outputs.NEXT_VERSION }}
      hasVersion: ${{ steps.get_next_version.outputs.HAS_NEXT_VERSION }}
    steps:
      - name: clone repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: download and use get-next-version
        run: |
          curl -L -o get-next-version https://github.com/thenativeweb/get-next-version/releases/download/2.1.2/get-next-version-linux-amd64
          chmod a+x get-next-version
          NEXT_VERSION_JSON=$(./get-next-version --format json)
          echo $NEXT_VERSION_JSON
          echo "NEXT_VERSION=v$(echo $NEXT_VERSION_JSON | jq -r ".version" -)" >> $GITHUB_OUTPUT
          echo "HAS_NEXT_VERSION=$(echo $NEXT_VERSION_JSON | jq -r ".hasNextVersion" -)" >> $GITHUB_OUTPUT
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - run: go test ./...
      - run: go build ./cmd/gbf
